### ISSUE TITLE
Example code doesn't compile

### ISSUE THREAD

**Issue by onx2** [ohmree/tide-governor#2]
Cool crate! I'd love to use this but I'm getting an error running the basic example that you have here. Any idea what might be going on? When I copy the code for this crate locally and use that, it works 🤷🏼 

```rust
use tide_governor::GovernorMiddleware;
use std::env;

#[async_std::main]
async fn main() -> tide::Result<()> {
    let mut app = tide::new();
    app.at("/")
        .with(GovernorMiddleware::per_minute(4)?)
        .get(|_| async move { todo!() });
    app.at("/foo/:bar")
        .with(GovernorMiddleware::per_hour(360)?)
        .put(|_| async move { todo!() });

    app.listen(format!("http://localhost:{}", env::var("PORT")?))
        .await?;
    Ok(())
}
```

```
expected a `Fn<(tide::Request<()>, Next<'a, ()>)>` closure, found `GovernorMiddleware`
the trait `for<'a> Fn<(tide::Request<()>, Next<'a, ()>)>` is not implemented for `GovernorMiddleware`
required because of the requirements on the impl of `Middleware<()>` for `GovernorMiddleware`
```

**Comment by ohmree** [comment]
Thanks for trying out my (admittedly scuffed) stuff!

As you can probably see I haven't touched it in a while but I'll try out the code and see if I can reproduce and fix the issue.

EDIT: a while back I merged a PR but forgot to publish a new release. Have you tried to use the latest version from github?
I'm still gonna get to the root of this but this is just a hunch I have.

**Comment by ohmree** [comment]
I published a new release that should fix this, please reopen if the issue persists.

**Comment by onx2** [comment]
Thanks! `1.0.3` is working great 😃
